# customer owns schema.rb

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: unibus_development
  url: <%= ENV['DATABASE_URL'] || 'postgresql://localhost/unibus_development' %>

test:
  <<: *default
  database: unibus_test
  url: <%= ENV['DATABASE_URL'] || 'postgresql://localhost/unibus_customer_test' %>

production:
  <<: *default
  database: unibus_production
  url: <%= ENV['DATABASE_URL'] %>
